services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - APP_NAME=${APP_NAME}
    volumes:
      - .:/var/www/${APP_NAME}
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf.template
    depends_on:
      - php
      - db
      - redis

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_SSL_MODE: 'DISABLED'
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        APP_NAME: ${APP_NAME}
    volumes:
      - .:/var/www/${APP_NAME}
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    entrypoint: ["/bin/sh", "-c", "redis-server & sleep 2 && redis-cli FLUSHALL && tail -f /dev/null"]

  tests:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/${APP_NAME}
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_CHARSET: utf8mb4

volumes:
  db_data: